# Tratamento

In [17]:
import pandas as pd
import numpy as np


df = pd.read_excel('casas.xlsx')
# df = df.drop(df.tail(5).index)

In [18]:
# Função de separar 2 números com - e retornar a média

def calcular_media_intervalo(valor):
    if pd.isna(valor):  
        return 0
    valor = str(valor)
    if '-' in valor:
        partes = valor.split('-')
        return np.mean([float(parte) for parte in partes])
    return float(valor)

In [19]:
# Arrumar a coluna metragem, quartos, banheiros e vagas

df['metragem'] = df['metragem'].str.replace('Tamanho do imóvel\n', '', regex=False).str.replace('m²', '', regex=False)
df['metragem'] = df['metragem'].apply(calcular_media_intervalo)
df['metragem'] = df['metragem'].astype(float)

df['quartos'] = df['quartos'].str.replace('Quantidade de quartos\n', '', regex=False).fillna(0)
df['quartos'] = df['quartos'].apply(calcular_media_intervalo) 
df['quartos'] = df['quartos'].astype(float) 

df['banheiros'] = df['banheiros'].str.replace('Quantidade de banheiros\n', '', regex=False).fillna(0)
df['banheiros'] = df['banheiros'].apply(calcular_media_intervalo) 
df['banheiros'] = df['banheiros'].astype(float) 

df['vagas'] = df['vagas'].str.replace('Quantidade de vagas de garagem\n', '', regex=False).fillna(0)
df['vagas'] = df['vagas'].apply(calcular_media_intervalo) 
df['vagas'] = df['vagas'].astype(float)

In [20]:
# Separando o IPTU e o condominio do valor e transformando em float

df['condominio'] = df['valor'].str.extract(r'Cond\. R\$ ([\d.,]+)')[0].str.replace('.', '', regex=False).str.replace(',', '.', regex=False).astype(float).fillna(0)
df['iptu'] = df['valor'].str.extract(r'IPTU R\$ ([\d.,]+)')[0].str.replace('.', '', regex=False).str.replace(',', '.', regex=False).astype(float).fillna(0)
df['valor'] = df['valor'].str.extract(r'R\$ ([\d.,]+)')[0].str.replace('.', '', regex=False).str.replace(',', '.', regex=False).astype(float)

In [21]:
# normalizando o nomeRua
df['nomeRua'] = df['nomeRua'].fillna('Rua não encontrada').str.capitalize().str.strip()

In [22]:
# Renomeando a coluna metragem
df.rename(columns={'metragem': 'metragem(m²)'}, inplace=True)

In [23]:
# visualização 
display(df)

,metragem(m²),quartos,banheiros,vagas,valor,nomeRua,condominio,iptu
0,604.0,4.0,7.0,3.0,11800000.0,Alameda mamoré,1659.0,873.0
1,60.0,2.0,2.0,1.0,395000.0,Rua marília,120.0,130.0
2,75.0,0.0,1.0,2.0,350000.0,Avenida valentim magalhães,0.0,0.0
3,43.0,1.0,1.5,1.0,180000.0,Rua general osório,430.0,67.0
4,161.0,3.0,1.0,0.0,265600.0,Rua não encontrada,0.0,0.0
...,...,...,...,...,...,...,...,...
100,27.0,2.0,1.0,1.0,199900.0,Rua general sousa neto,0.0,0.0
101,525.0,0.0,0.0,0.0,270000.0,Rua geraldo vieira dos santos,550.0,0.0
102,37.0,2.0,1.0,0.0,273000.0,Avenida giovanni gronchi,0.0,0.0
103,146.0,3.0,3.0,2.0,1899970.0,Avenida jamaris,2000.0,700.0
104,400.0,0.0,0.0,0.0,480000.0,Avenida hélio borenstein,0.0,2459.0

In [24]:
# Salvar em um novo excel

df.to_excel('casas_limpo.xlsx', index=False)